DELETE FROM stg.D_SAN_PHAM_TEMP
WHERE etl_date >= TO_DATE('{{ params.runday }}', 'YYYY/MM/DD') ;

INSERT INTO stg.D_SAN_PHAM_TEMP
(   
    MA_SAN_PHAM,
    TEN_SAN_PHAM,
    MA_LOAI_HANG,
    TEN_LOAI_HANG,
    MO_TA_LOAI_HANG,
    MA_TRANG_THAI,
    TRANG_THAI,
    MO_TA_TRANG_THAI,
    MA_PL_NGANH_HANG,
    TEN_PL_NGANH_HANG,
    MA_NHOM_SAN_PHAM,
    TEN_NHOM_SAN_PHAM,
    MA_NHOM_HANG,
    TEN_NHOM_HANG,
    MA_NGANH_HANG,
    TEN_NGANH_HANG,
    BIEN_THE,
    MA_THUONG_HIEU,
    TEN_THUONG_HIEU,
    MA_DON_VI_LE,
    TEN_DON_VI_LE,
    CO_DONG_GOI,
    MA_DON_VI_TINH,
    TEN_DON_VI_TINH,
    MA_PACKSIZE,
    TEN_PACKSIZE,
    MA_DON_VI_CHAN,
    TEN_DON_VI_CHAN,
    QUY_CACH_DONG_GOI,
    TONG_TRONG_LUONG,
    MA_HINH_THUC_DONG_GOI,
    TEN_HINH_THUC_DONG_GOI,
    MA_NGUON_GOC_SAN_PHAM,
    MA_VACH,
    TEN_NGUON_GOC,
    BARCODE_SAN_PHAM,
    BARCODE_THUNG,
    MA_NCC_SAN_PHAM,
    TEN_DK_KINH_DOANH,
    TEN_VIET_TAT,
    LOAI_NCC,
    MST,
    SDT,
    DIA_CHI,
    GHI_CHU,
    NHA_SAN_XUAT,
    MA_MO_HINH_MUA,
    TEN_MO_HINH_MUA,
    NGON_NGU_SAN_PHAM,
    HAN_SU_DUNG,
    ETL_DATE
)
(
SELECT
    UPPER(TRIM(S1.MA_SAN_PHAM)) AS MA_SAN_PHAM,
    S1.TEN_SAN_PHAM,
    UPPER(TRIM(S1.MA_LOAI_HANG)) AS MA_LOAI_HANG,
    S11.TEN_LOAI_HANG AS TEN_LOAI_HANG,
    S11.MO_TA AS MO_TA_LOAI_HANG,
    UPPER(TRIM(S1.MA_TRANG_THAI)) AS MA_TRANG_THAI,
    S2.TRANG_THAI AS TRANG_THAI,
    S2.MO_TA AS MO_TA_TRANG_THAI,
    UPPER(TRIM(S1.MA_PL_NGANH_HANG)) AS MA_PL_NGANH_HANG,
    S7.TEN_PL_NGANH_HANG as TEN_PL_NGANH_HANG,
    UPPER(TRIM(S1.MA_NHOM_SAN_PHAM)) AS MA_NHOM_SAN_PHAM,
    S9.TEN_NHOM_SAN_PHAM AS TEN_NHOM_SAN_PHAM,
    UPPER(TRIM(S9.MA_NHOM_HANG)) AS MA_NHOM_HANG,
    S9.TEN_NHOM_HANG AS TEN_NHOM_HANG,
    UPPER(TRIM(S9.MA_NGANH_HANG)) AS MA_NGANH_HANG,
    S9.TEN_NGANH_HANG AS TEN_NGANH_HANG,
    S1.BIEN_THE,
    UPPER(TRIM(S1.MA_THUONG_HIEU)) AS MA_THUONG_HIEU,
    S10.TEN_THUONG_HIEU AS TEN_THUONG_HIEU,
    UPPER(TRIM(S1.MA_DVL)) AS MA_DON_VI_LE,
    S12.TEN_DON_VI as TEN_DON_VI_LE,
    UPPER(TRIM(S1.CO_DONG_GOI)) AS CO_DONG_GOI,
    UPPER(TRIM(S1.MA_DVT)) AS MA_DON_VI_TINH,
    S4.TEN_DVT as TEN_DON_VI_TINH,
    UPPER(TRIM(S1.MA_PACKSIZE)) AS MA_PACKSIZE,
    S3.TEN_PACKSIZE AS TEN_PACKSIZE,
    UPPER(TRIM(S1.MA_DVC)) AS MA_DON_VI_CHAN,
    S13.TEN_DON_VI AS TEN_DON_VI_CHAN,
    S1.QUY_CACH_DONG_GOI,
    CASE
        WHEN TONG_TRONG_LUONG = '#VALUE!' then NULL
        ELSE TONG_TRONG_LUONG
    END AS TONG_TRONG_LUONG,
    UPPER(TRIM(S1.MA_HINH_THUC_DONG_GOI)) AS MA_HINH_THUC_DONG_GOI,
    S5.TEN_HT_DONG_GOI AS TEN_HINH_THUC_DONG_GOI,
    UPPER(TRIM(S1.MA_NGUON_GOC_SAN_PHAM)) AS MA_NGUON_GOC_SAN_PHAM,
    S6.MA_VACH AS MA_VACH,
    S6.TEN_NGUON_GOC AS TEN_NGUON_GOC,
    S1.BARCODE_SAN_PHAM,
    S1.BARCODE_THUNG,
    UPPER(TRIM(S1.MA_NCC_SAN_PHAM)) AS MA_NCC_SAN_PHAM,
    S14.TEN_DK_KINH_DOANH AS TEN_DK_KINH_DOANH,
    S14.TEN_VIET_TAT AS TEN_VIET_TAT,
    S14.LOAI_NCC AS LOAI_NCC ,
    S14.MST AS MST ,
    S14.SDT AS SDT ,
    S14.DIA_CHI AS DIA_CHI ,
    S14.GHI_CHU AS GHI_CHU ,
    S1.NHA_SAN_XUAT,
    UPPER(TRIM(S1.MA_MO_HINH_MUA)) AS MA_MO_HINH_MUA,
    S8.TEN_MO_HINH_MUA AS TEN_MO_HINH_MUA,
    S1.NGON_NGU_SAN_PHAM,
    S1.HAN_SU_DUNG,
    S1.etl_date
FROM stg.D_SAN_PHAM S1
LEFT JOIN stg.D_TRANG_THAI_SP S2 ON UPPER(TRIM(S1.MA_TRANG_THAI)) = S2.MA_TRANG_THAI and s1.etl_date = s2.etl_date 
LEFT JOIN stg.D_PACKSIZE S3 ON UPPER(TRIM(S1.MA_PACKSIZE)) = S3.MA_PACKSIZE and s1.etl_date = s3.etl_date 
LEFT JOIN stg.D_DON_VI_TINH S4 ON UPPER(TRIM(S1.MA_DVT)) = S4.MA_DVT AND S1.etl_date = S4.etl_date
LEFT JOIN stg.D_HT_DONG_GOI S5 ON UPPER(TRIM(S1.MA_HINH_THUC_DONG_GOI)) = S5.MA_HT_DONG_GOI AND S1.etl_date = S5.etl_date
LEFT JOIN stg.D_NGUON_GOC_SP S6 ON UPPER(TRIM(S1.MA_NGUON_GOC_SAN_PHAM)) = S6.MA_NGUON_GOC AND S1.etl_date = S6.etl_date
LEFT JOIN stg.D_PHAN_LOAI_NGANH_HANG S7 ON UPPER(TRIM(S1.MA_PL_NGANH_HANG)) = S7.MA_PL_NGANH_HANG AND S1.etl_date = S7.etl_date
LEFT JOIN stg.D_MO_HINH_MUA S8 ON UPPER(TRIM(S1.MA_MO_HINH_MUA)) = S8.MA_MO_HINH_MUA AND S1.etl_date = S8.etl_date
LEFT JOIN stg.D_CAY_NHOM_SAN_PHAM S9 ON UPPER(TRIM(S1.MA_NHOM_SAN_PHAM)) = S9.MA_NHOM_SAN_PHAM AND S1.etl_date = S9.etl_date
LEFT JOIN stg.D_THUONG_HIEU S10 ON UPPER(TRIM(S1.MA_THUONG_HIEU)) = S10.MA_THUONG_HIEU AND S1.etl_date = S10.etl_date
LEFT JOIN stg.D_LOAI_HANG S11 ON UPPER(TRIM(S1.MA_LOAI_HANG)) = S11.MA_LOAI_HANG AND S1.etl_date = S11.etl_date
LEFT JOIN stg.D_DON_VI_DG S12 ON UPPER(TRIM(S1.MA_DVL)) = S12.MA_DON_VI AND S1.etl_date = S12.etl_date
LEFT JOIN stg.D_DON_VI_DG S13 ON UPPER(TRIM(S1.MA_DVC)) = S13.MA_DON_VI AND S1.etl_date = S13.etl_date
LEFT JOIN stg.D_NCC_SP S14 ON UPPER(TRIM(S1.MA_NCC_SAN_PHAM)) = S14.MA_NCC AND  S1.etl_date = S14.etl_date
where s1.etl_date = TO_DATE('{{ params.runday }}', 'YYYY/MM/DD') 
);

DELETE FROM stg.D_SAN_PHAM_TEMP
WHERE etl_date <= TO_DATE('{{ params.runday }}', 'YYYY/MM/DD') - INTERVAL '3 DAY';

 