CREATE TABLE mdm.nhom_san_pham (
    MA_NHOM_SAN_PHAM TEXT PRIMARY KEY,
    TEN_NHOM_SAN_PHAM TEXT,
    MA_NHOM_SAN_PHAM_CHA TEXT,
    FOREIGN KEY (MA_NHOM_SAN_PHAM_CHA) REFERENCES mdm.nhom_san_pham(MA_NHOM_SAN_PHAM)
);