CREATE TABLE mdm.san_pham (
	ma_san_pham text NULL,
	ten_san_pham text NULL,
	ma_loai_hang text NULL,
	ma_trang_thai text NULL,
	ma_pl_nganh_hang text NULL,
	ma_nhom_san_pham text NULL,
	bien_the text NULL,
	ma_thuong_hieu text NULL,
	ma_dvl text NULL,
	co_dong_goi text NULL,
	ma_dvt text NULL,
	ma_packsize text NULL,
	ma_dvc text NULL,
	quy_cach_dong_goi float8 NULL,
	tong_trong_luong text NULL,
	ma_hinh_thuc_dong_goi text NULL,
	ma_nguon_goc_san_pham text NULL,
	barcode_san_pham float8 NULL,
	barcode_thung float8 NULL,
	ma_ncc_san_pham text NULL,
	nha_san_xuat text NULL,
	ma_mo_hinh_mua text NULL,
	ngon_ngu_san_pham text NULL,
	han_su_dung float8 NULL,
    FOREIGN KEY (MA_LOAI_HANG) REFERENCES mdm.loai_hang(MA_LOAI_HANG),
    FOREIGN KEY (MA_TRANG_THAI) REFERENCES mdm.trang_thai_sp(MA_TRANG_THAI),
    FOREIGN KEY (MA_PL_NGANH_HANG) REFERENCES mdm.phan_loai_nganh_hang(MA_PL_NGANH_HANG),
    FOREIGN KEY (MA_NHOM_SAN_PHAM) REFERENCES mdm.nhom_san_pham(MA_NHOM_SAN_PHAM),
    FOREIGN KEY (MA_THUONG_HIEU) REFERENCES mdm.thuong_hieu(MA_THUONG_HIEU),
    FOREIGN KEY (MA_DVL) REFERENCES mdm.don_vi_dg(MA_DON_VI),
    FOREIGN KEY (MA_DVT) REFERENCES mdm.don_vi_tinh(MA_DVT),
    FOREIGN KEY (MA_DVC) REFERENCES mdm.don_vi_dg(MA_DON_VI),
    FOREIGN KEY (MA_PACKSIZE) REFERENCES mdm.packsize(MA_PACKSIZE),
    FOREIGN KEY (MA_HINH_THUC_DONG_GOI) REFERENCES mdm.ht_dong_goi(MA_HT_DONG_GOI),
    FOREIGN KEY (MA_NGUON_GOC_SAN_PHAM) REFERENCES mdm.nguon_goc_sp(MA_NGUON_GOC),
    FOREIGN KEY (MA_NCC_SAN_PHAM) REFERENCES mdm.ncc_sp(MA_NCC),
    FOREIGN KEY (MA_MO_HINH_MUA) REFERENCES mdm.mo_hinh_mua(MA_MO_HINH_MUA)
);